name: Publish and Create Release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.33.0

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint, Test, and Build
        run: pnpm exec turbo run lint build test
