name: Publish and Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.13.1
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          cd packages/zustand-debounce
          pnpm run build

      - name: Copy README.md to package directory
        run: cp README.md packages/zustand-debounce/README.md

      - name: Publish to npm
        run: |
          cd packages/zustand-debounce
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes